### PR TITLE
Trans fix

### PR DESCRIPTION
**Pull request by Slavka-JD**
https://app.asana.com/0/25002076043610/29842058341571

### CODE REVIEW

**Comment by mushkin-v** [comment]
DONT MERGE!

**Comment by mushkin-v** [comment]
I will add it in my PR "translations"  dont merge it in develop

**Comment by mushkin-v** [comment]
You again update composer.lock! We cant merge you PR at all....

**Comment by Slavka-JD** [comment]
Where exactly have I updated it? I see no changes of composer.lock in my commits

**Comment by mushkin-v** [comment]
Forget it, we wount merge this... I just take helpfull data from here to my PR....

**Pull request closed without merging**
